# Generated by Django 3.0.6 on 2020-05-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=120)),
                ('device_description', models.TextField()),
                ('device_in_used', models.BooleanField(default=True)),
            ],
        ),
    ]
